apiVersion: v1
data:
  production.toml: |
    [server]
    port = 5000
    host = "0.0.0.0"

    [metrics_server]
    host = "0.0.0.0"
    port = 6128

    [pool_config]
    pool = 2

    [log]
    log_format = "json"
    log_level = "debug"

    [database]
    user = {{ include "keymanager-psql.username" . }}
    host = {{ include "keymanager-psql.host" . }}
    port = {{ include "keymanager-psql.port" . }}
    dbname = {{ include "keymanager-psql.database" . }}
    pool_size = 5
    min_idle = 2
    enable_ssl = {{ include "keymanager-psql.enable_ssl" . }}

    [multitenancy.tenants.public]
    cache_prefix = "{{ .Values.multitenancy.tenants.public.cache_prefix}}"
    schema = "{{ .Values.multitenancy.tenants.public.schema }}"
    
    [multitenancy.tenants.global]
    cache_prefix = "{{ .Values.multitenancy.tenants.global.cache_prefix}}"
    schema = "{{ .Values.multitenancy.tenants.global.schema }}"


kind: ConfigMap
metadata:
  name: keymanager-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
