apiVersion: v1
data:
  CRIPTA__SECRETS__ACCESS_TOKEN: {{ .Values.secrets.access_token | b64enc }}
  CRIPTA__SECRETS__HASH_CONTEXT: {{ .Values.secrets.hash_context | b64enc }}
  
  {{- if .Values.postgresql.enabled }}
  password: {{ include "keymanager-psql.password" . | b64enc }}
  {{- else if .Values.external.postgresql.enabled }}
  password: {{ include "keymanager-psql.password" . | b64enc }}
  primaryPlainPassword: {{ include "keymanager-psql.plainpassword" . | b64enc }}
  {{- end }}
  
  CRIPTA__DATABASE__PASSWORD: {{ include "keymanager-psql.password" . | b64enc }}
  {{- if .Values.secrets.database.root_ca }}
  CRIPTA__DATABASE__ROOT_CA: {{ .Values.secrets.database.root_ca | b64enc }}
  {{- end }}
  
  {{- if eq .Values.backend "aws" }}
  CRIPTA__SECRETS__KMS_CONFIG__KEY_ID: {{ .Values.secrets.aws.key_id | b64enc }}
  CRIPTA__SECRETS__KMS_CONFIG__REGION: {{ .Values.secrets.aws.region | b64enc }}
  {{- else if eq .Values.backend "vault" }}
  CRIPTA__SECRETS__VAULT_CONFIG__VAULT_TOKEN: {{ .Values.secrets.vault.token | b64enc }}
  {{- else if eq .Values.backend "local" }}
  CRIPTA__SECRETS__MASTER_KEY: {{ .Values.secrets.master_key | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.tls.cert }}
  CRIPTA__CERTS__TLS_CERT: {{ .Values.secrets.tls.cert | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tls.key }}
  CRIPTA__CERTS__TLS_KEY: {{ .Values.secrets.tls.key | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tls.ca }}
  CRIPTA__CERTS__ROOT_CA: {{ .Values.secrets.tls.ca | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: keymanager-secrets-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
