{{- if eq .Values.backend "aws" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.server.annotations }}
  annotations:
    {{- toYaml .Values.server.annotations | nindent 4 }}
  {{- end }}
  name: keymanager-role
  namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keymanager-role
  namespace: {{ .Release.Namespace }}
{{- end }}
