# Release notes configuration
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 📦 Dependency Updates
      labels:
        - dependencies
        - deps
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
    - title: 🔒 Security
      labels:
        - security
    - title: Other Changes
      labels:
        - "*"