apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  {{- with (default .Values.global.annotations .Values.server.serviceAccountAnnotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: hyperswitch-router-role
  namespace: {{ .Release.Namespace }}

