{{- if index .Values "kube-prometheus-stack" "enabled" }}
{{- if index .Values "kube-prometheus-stack" "grafana" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperswitch-monitoring.fullname" . }}-grafana-datasources
  labels:
    {{- include "hyperswitch-monitoring.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ include "hyperswitch-monitoring.prometheus.url" . }}
        isDefault: true
        uid: "prometheus"
      - name: Loki
        type: loki
        access: proxy
        url: {{ include "hyperswitch-monitoring.loki.url" . }}
        uid: "loki"
        isDefault: false
      - name: PostgreSQL
        type: postgres
        access: proxy
        url: {{ include "hyperswitch-monitoring.postgresql.hostname" . }}:{{ include "hyperswitch-monitoring.postgresql.port" . }}
        user: {{ include "hyperswitch-monitoring.postgresql.username" . }}
        password: {{ include "hyperswitch-monitoring.postgresql.password" . }}
        database: {{ include "hyperswitch-monitoring.postgresql.database" . }}
        uid: postgres_uid
        jsonData:
          sslmode: "disable"
        secureJsonData:
          password: {{ include "hyperswitch-monitoring.postgresql.password" . }}
 
{{- end }}
{{- end }}
