apiVersion: v1
kind: ConfigMap
metadata:
  name: ucs-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  production.toml: |
    [log.console]
    enabled = {{ .Values.config.log.console.enabled }}
    level = "{{ .Values.config.log.console.level }}"
    log_format = "{{ .Values.config.log.console.log_format }}"

    [server]
    host = "{{ .Values.config.server.host }}"
    port = {{ .Values.config.server.port }}
    type = "{{ .Values.config.server.type }}"

    [metrics]
    host = "{{ .Values.config.metrics.host }}"
    port = {{ .Values.config.metrics.port }}

    [connectors]
    adyen.base_url = "{{ .Values.config.connectors.adyen.base_url }}"
    adyen.dispute_base_url = "{{ .Values.config.connectors.adyen.dispute_base_url }}"
    razorpay.base_url = "{{ .Values.config.connectors.razorpay.base_url }}"
    fiserv.base_url = "{{ .Values.config.connectors.fiserv.base_url }}"
    elavon.base_url = "{{ .Values.config.connectors.elavon.base_url }}"
    xendit.base_url = "{{ .Values.config.connectors.xendit.base_url }}"
    razorpayv2.base_url = "{{ .Values.config.connectors.razorpayv2.base_url }}"
    checkout.base_url = "{{ .Values.config.connectors.checkout.base_url }}"
    authorizedotnet.base_url = "{{ .Values.config.connectors.authorizedotnet.base_url }}"

    [proxy]
    https_url = "{{ .Values.config.proxy.https_url }}"
    http_url = "{{ .Values.config.proxy.http_url }}"
    idle_pool_connection_timeout = {{ .Values.config.proxy.idle_pool_connection_timeout }}
    bypass_proxy_urls = {{ .Values.config.proxy.bypass_proxy_urls | toJson }}
