apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperswitch-ucs.fullname" . }}
  labels:
    {{- include "hyperswitch-ucs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hyperswitch-ucs.selectorLabels" . | nindent 4 }}