apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hyperswitch-server-destinations
  namespace: hyperswitch
spec:
  exportTo:
  - '*'
  host: hyperswitch-server
  subsets:
  - labels:
      version: {{ .Values.image.version }}
    name: {{ .Values.image.version }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
