apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hyperswitch-application-server
  namespace: hyperswitch
spec:
  gateways:
  - istio-system/hyperswitch-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /sample_data
    rewrite:
      uri: /not/authorization
    route:
    - destination:
        host: hyperswitch-server
        subset: {{ .Values.image.version }}
      weight: 100
    timeout: 50s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hyperswitch-server
        subset: {{ .Values.image.version }}
      weight: 100
    timeout: 50s
