apiVersion: v1
data:
  development.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080

    [secrets]
    tenant = "hyperswitch"
kind: ConfigMap
metadata:
  name: hyperswitch-vault-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
