name: Lint and Test Charts

on:
  workflow_call:
    inputs:
      ct_configfile:
        description: location of the ct config file
        default: ct.yaml
        required: false
        type: string
      ct_check_version_increment:
        description: whether to check for version bump requirement
        default: true
        required: false
        type: boolean
      helm_version:
        description: version of the helm binary
        default: v3.14.0
        required: false
        type: string
      kind_kubectl_version:
        description: version of the kubectl binary used for the kind cluster
        required: false
        type: string
      kind_node_image:
        description: image reference for the node containers in the kind_cluster
        required: false
        type: string

env:
  CT_CONFIGFILE: ${{ inputs.ct_configfile }}
  CT_CHECK_VERSION_INCREMENT: ${{ inputs.ct_check_version_increment }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ inputs.helm_version }}

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config "${CT_CONFIGFILE}")
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config "${CT_CONFIGFILE}" --check-version-increment="${CT_CHECK_VERSION_INCREMENT}"

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          kubectl_version: ${{ inputs.kind_kubectl_version }}
          node_image: ${{ inputs.kind_node_image }}

      - name: Run chart-testing (install)
        run: |
          changed=$(ct list-changed --config "${CT_CONFIGFILE}")

          # List of charts to skip
          skip_charts=(
            "charts/incubator/hyperswitch-istio"
            "charts/incubator/hyperswitch-keymanager"
            "charts/incubator/hyperswitch-web"
          )

          # Filter the list
          filtered_charts=()
          for chart in $changed; do
            skip=false
            for skip_chart in "${skip_charts[@]}"; do
              if [[ "$chart" == "$skip_chart" ]]; then
                echo "Skipping $chart"
                skip=true
                break
              fi
            done
            if ! $skip; then
              filtered_charts+=("$chart")
            fi
          done

          # Exit if nothing to install
          if [ ${#filtered_charts[@]} -eq 0 ]; then
            echo "No charts to install after filtering."
            exit 0
          fi

          echo "Creating required namespaces..."
          kubectl create namespace hyperswitch || true

          # Run `ct install` only on filtered charts
          ct install --config "${CT_CONFIGFILE}" --charts "${filtered_charts[@]}"
