name: Lint and Test Charts

on:
  workflow_call:
    inputs:
      ct_configfile:
        description: location of the ct config file
        default: ct.yaml
        required: false
        type: string
      ct_check_version_increment:
        description: whether to check for version bump requirement
        default: true
        required: false
        type: boolean
      helm_version:
        description: version of the helm binary
        default: v3.14.0
        required: false
        type: string
      kind_kubectl_version:
        description: version of the kubectl binary used for the kind cluster
        required: false
        type: string
      kind_node_image:
        description: image reference for the node containers in the kind_cluster
        required: false
        type: string

env:
  CT_CONFIGFILE: ${{ inputs.ct_configfile }}
  CT_CHECK_VERSION_INCREMENT: ${{ inputs.ct_check_version_increment }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ inputs.helm_version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Detect changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config "${CT_CONFIGFILE}")
          echo "changed=$([[ -n \"$changed\" ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"

  version-check:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ inputs.helm_version }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Version Increment Check
        run: ct lint --config "${CT_CONFIGFILE}" --check-version-increment=true

  lint:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ inputs.helm_version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Lint Charts
        run: ct lint --config "${CT_CONFIGFILE}"

  install-test:
    needs: [setup, lint]
    runs-on: ubuntu-latest
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ inputs.helm_version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          kubectl_version: ${{ inputs.kind_kubectl_version }}
          node_image: ${{ inputs.kind_node_image }}

      - name: Run chart install tests
        run: |
          changed=$(ct list-changed --config "${CT_CONFIGFILE}")

          skip_charts=(
            "charts/incubator/hyperswitch-istio"
            "charts/incubator/hyperswitch-keymanager"
            "charts/incubator/hyperswitch-web"
          )

          filtered_charts=()
          for chart in $changed; do
            skip=false
            for skip_chart in "${skip_charts[@]}"; do
              if [[ "$chart" == "$skip_chart" ]]; then
                echo "Skipping $chart"
                skip=true
                break
              fi
            done
            if ! $skip; then
              filtered_charts+=("$chart")
            fi
          done

          if [ ${#filtered_charts[@]} -eq 0 ]; then
            echo "No charts to install after filtering."
            exit 0
          fi

          kubectl create namespace hyperswitch || true

          ct install --config "${CT_CONFIGFILE}" --charts "${filtered_charts[@]}"
