name: PR Title Convention Check

on:
  pull_request:
    types: [opened, edited, synchronize]

# Add permissions for the GITHUB_TOKEN
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Convention
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;

            // Define allowed prefixes (conventional commit types)
            const allowedPrefixes = [
              'feat', 'fix', 'docs', 'style', 'refactor',
              'test', 'chore', 'perf', 'ci', 'build',
              'revert', 'hotfix'
            ];

            // Define the regex pattern for PR title validation
            // Format: type(scope): description
            // Examples:
            // - feat: add user authentication
            // - fix(api): resolve timeout issue
            // - docs(readme): update installation guide
            const titleRegex = /^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert|hotfix)(\(.+\))?: .+/;

            console.log(`Checking PR title: "${title}"`);

            if (!titleRegex.test(title)) {
              const errorMessage = `
              ❌ **PR Title Convention Check Failed**

              Your PR title "${title}" doesn't follow the required convention.

              **Required format:** \`type(scope): description\`

              **Valid types:**
              ${allowedPrefixes.map(type => `- \`${type}\``).join('\n')}

              **Examples of valid titles:**
              - \`feat: add user authentication system\`
              - \`fix(api): resolve database connection timeout\`
              - \`docs(readme): update installation instructions\`
              - \`refactor(components): simplify button styling\`
              - \`test: add unit tests for user service\`

              **Rules:**
              - Type must be one of the allowed types above
              - Scope is optional but should be in parentheses if used
              - Description must start with lowercase letter
              - No period at the end
              - Keep it concise but descriptive

              Please update your PR title to follow this convention.
              `;

              // Try to add comment to PR, but don't fail if permissions are insufficient
              try {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: errorMessage
                });
                console.log('Comment posted successfully');
              } catch (error) {
                console.log('Could not post comment due to permissions:', error.message);
                console.log('Error details will be shown in the check failure message instead');
              }

              // Fail the check with detailed message
              core.setFailed(`PR title "${title}" doesn't follow the required convention. Required format: type(scope): description. Valid types: ${allowedPrefixes.join(', ')}`);
            } else {
              console.log('✅ PR title follows the required convention!');

              // Try to add success comment, but don't fail if permissions are insufficient
              try {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '✅ **PR Title Convention Check Passed** - Thank you for following the naming convention!'
                });
              } catch (error) {
                console.log('Could not post success comment due to permissions, but check passed');
              }
            }
