apiVersion: v1
entries:
  hyperswitch-keymanager:
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2025-06-29T19:23:58.322939+05:30"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.5.38
    description: A Helm chart for deploying Hyperswitch Keymanager
    digest: 3622fd31aa6b7245718626caee35cdf80d476debf50001a2615379b239379fe6
    name: hyperswitch-keymanager
    type: application
    urls:
    - https://juspay.github.io/hyperswitch-helm/charts/incubator/hyperswitch-keymanager/hyperswitch-keymanager-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r30
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-12-r43
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.4.0-debian-12-r14
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.4.0
    created: "2025-06-29T19:23:58.330154+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 6537de714df16f71c720921bd0ad8fad90bb01525fb3aacff3503781de3f9f8b
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-15.5.38.tgz
    version: 15.5.38
generated: "2025-06-29T19:23:58.310363+05:30"
