apiVersion: v1
entries:
  hyperswitch-card-vault:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-06-28T20:28:30.842006+05:30"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.5.38
    description: A Helm chart for creating Hyperswitch Card Vault
    digest: 3ea3f9b1860a0a910d6f48abc85409a55276e608481250eda00c2531dbca6bd1
    name: hyperswitch-card-vault
    type: application
    urls:
    - hyperswitch-card-vault-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r30
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-12-r43
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.4.0-debian-12-r14
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.4.0
    created: "2025-06-28T20:28:30.848273+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 6537de714df16f71c720921bd0ad8fad90bb01525fb3aacff3503781de3f9f8b
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-15.5.38.tgz
    version: 15.5.38
generated: "2025-06-28T20:28:30.827857+05:30"
